name: "combine-prs"
description: "Combine multiple PRs into a single PR"
author: "Grant Birkinbine"
branding:
  icon: 'git-branch'
  color: 'gray-dark'
inputs:
  github_token:
    description: The GitHub token used to create an authenticated client - Provided for you by default!
    default: ${{ github.token }}
    required: true
  branch_prefix:
    description: The prefix of the branches to combine
    required: true
    default: dependabot
  ci_required:
    description: Whether or not CI should be passing to combine the PR
    required: true
    default: "true"
  review_required:
    description: Whether or not a review should be required to combine the PR
    required: false
    default: "false"
  combine_branch_name:
    description: The name of the branch to combine the PRs into
    required: true
    default: "combined-prs-branch"
  ignore_label:
    description: The label to ignore when combining PRs
    required: true
    default: "nocombine"
outputs:
  pr_url:
    description: The pull request URL if a PR was created
  pr_number:
    description: The pull request number if a PR was created
runs:
  using: "node16"
  main: "dist/index.js"
