name: lint
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0

      # check the node version from the .node-version file
      - name: fetch node version
        id: node-version
        run: |
          version=$(cat .node-version)
          echo "version=${version}" >> $GITHUB_OUTPUT

      - name: setup node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ steps.node-version.outputs.version }}
          cache: npm

      - name: install dependencies
        run: npm ci

      - name: lint
        run: |
          npm run format-check
          npm run lint
