name: package-check

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  package-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # check the node version from the .node-version file
      - name: fetch node version
        id: node-version
        run: |
          version=$(cat .node-version)
          echo "version=${version}" >> $GITHUB_OUTPUT

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.node-version.outputs.version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Rebuild the dist/ directory
        run: npm run bundle

      - name: Compare the expected and actual dist/ directories
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff
            exit 1
          fi
        id: diff

      # If index.js was different than expected, upload the expected version as an artifact
      - uses: actions/upload-artifact@v3
        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
        with:
          name: dist
          path: dist/
