name: test
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # check the node version from the .node-version file
      - name: fetch node version
        id: node-version
        run: |
          version=$(cat .node-version)
          echo "version=${version}" >> $GITHUB_OUTPUT

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.node-version.outputs.version }}
          cache: npm

      - run: npm ci
      - run: npm run ci-test
